version: '3.8'
services: 
  client: 
    build: ./client
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network
  server:
    platform: linux/arm64
    cap_add:
      - SYS_ADMIN
    build: ./server
    ports:
      - "3001:3001" 
    networks:
      - app-network
    restart: always

networks:
      app-network:
        driver: bridge  