version: '3.8'
services: 
  client:
    build: ./client
    stdin_open: true
    ports:
      - "80:80"
    links:
      - "server:app-server"
  server:
    build: ./server
    ports:
      - "3001:3001" 